// src/currencyData.js

const majorCurrencies = {
  USD: { name: 'United States Dollar' },
  EUR: { name: 'Euro' },
  GBP: { name: 'British Pound Sterling' },
  JPY: { name: 'Japanese Yen' },
};

const otherCurrencies = {
  AUD: { name: 'Australian Dollar' },
  CAD: { name: 'Canadian Dollar' },
  CHF: { name: 'Swiss Franc' },
  CNY: { name: 'Chinese Yuan' },
  INR: { name: 'Indian Rupee' },
  BRL: { name: 'Brazilian Real' },
  RUB: { name: 'Russian Ruble' },
  ZAR: { name: 'South African Rand' },
  NZD: { name: 'New Zealand Dollar' },
  SEK: { name: 'Swedish Krona' },
  NOK: { name: 'Norwegian Krone' },
  MXN: { name: 'Mexican Peso' },
  SGD: { name: 'Singapore Dollar' },
  HKD: { name: 'Hong Kong Dollar' },
  KRW: { name: 'South Korean Won' },
  PLN: { name: 'Polish Zloty' },
  THB: { name: 'Thai Baht' },
  TRY: { name: 'Turkish Lira' },
  ILS: { name: 'Israeli New Shekel' },
  MYR: { name: 'Malaysian Ringgit' },
  PHP: { name: 'Philippine Peso' },
  DKK: { name: 'Danish Krone' },
  HUF: { name: 'Hungarian Forint' },
  CZK: { name: 'Czech Koruna' },
  AED: { name: 'United Arab Emirates Dirham' },
  ARS: { name: 'Argentine Peso' },
  CLP: { name: 'Chilean Peso' },
  COP: { name: 'Colombian Peso' },
  PEN: { name: 'Peruvian Sol' },
  SAR: { name: 'Saudi Riyal' },
  VND: { name: 'Vietnamese Dong' },
  BGN: { name: 'Bulgarian Lev' },
  RON: { name: 'Romanian Leu' },
  HNL: { name: 'Honduran Lempira' },
  TWD: { name: 'New Taiwan Dollar' },
  HRK: { name: 'Croatian Kuna' },
  PAB: { name: 'Panamanian Balboa' },
  UYU: { name: 'Uruguayan Peso' },
  DOP: { name: 'Dominican Peso' },
  CUC: { name: 'Cuban Convertible Peso' },
  KWD: { name: 'Kuwaiti Dinar' },
  BHD: { name: 'Bahraini Dinar' },
  KHR: { name: 'Cambodian Riel' },
  JMD: { name: 'Jamaican Dollar' },
  LKR: { name: 'Sri Lankan Rupee' },
  MUR: { name: 'Mauritian Rupee' },
  NGN: { name: 'Nigerian Naira' },
  XOF: { name: 'West African CFA Franc' },
  XAF: { name: 'Central African CFA Franc' },
  YER: { name: 'Yemeni Rial' },
  ZWL: { name: 'Zimbabwean Dollar' },
  BDT: { name: 'Bangladeshi Taka' },
  BYN: { name: 'Belarusian Ruble' },
  BMD: { name: 'Bermudian Dollar' },
  BND: { name: 'Brunei Dollar' },
  BWP: { name: 'Botswana Pula' },
  CDF: { name: 'Congolese Franc' },
  DZD: { name: 'Algerian Dinar' },
  EGP: { name: 'Egyptian Pound' },
  ETB: { name: 'Ethiopian Birr' },
  FJD: { name: 'Fijian Dollar' },
  GHS: { name: 'Ghanaian Cedi' },
  GMD: { name: 'Gambian Dalasi' },
  GNF: { name: 'Guinean Franc' },
  GTQ: { name: 'Guatemalan Quetzal' },
  HTG: { name: 'Haitian Gourde' },
  IQD: { name: 'Iraqi Dinar' },
  JOD: { name: 'Jordanian Dinar' },
  KES: { name: 'Kenyan Shilling' },
  KZT: { name: 'Kazakhstani Tenge' },
  LBP: { name: 'Lebanese Pound' },
  LSL: { name: 'Lesotho Loti' },
  LYD: { name: 'Libyan Dinar' },
  MAD: { name: 'Moroccan Dirham' },
  MDL: { name: 'Moldovan Leu' },
  MGA: { name: 'Malagasy Ariary' },
  MNT: { name: 'Mongolian Tugrik' },
  MOP: { name: 'Macanese Pataca' },
  MWK: { name: 'Malawian Kwacha' },
  OMR: { name: 'Omani Rial' },
  PGK: { name: 'Papua New Guinean Kina' },
  QAR: { name: 'Qatari Rial' },
  RSD: { name: 'Serbian Dinar' },
  RWF: { name: 'Rwandan Franc' },
  SLL: { name: 'Sierra Leonean Leone' },
  SOS: { name: 'Somali Shilling' },
  SSP: { name: 'South Sudanese Pound' },
  SZL: { name: 'Swazi Lilangeni' },
  TZS: { name: 'Tanzanian Shilling' },
  UGX: { name: 'Ugandan Shilling' },
  UZS: { name: 'Uzbekistani Som' },
  VUV: { name: 'Vanuatu Vatu' },
  WST: { name: 'Samoan Tala' },
  XCD: { name: 'East Caribbean Dollar' },
  XPF: { name: 'CFP Franc' },
  ZMW: { name: 'Zambian Kwacha' },
};

const cryptocurrencies = {
  BTC: { name: 'Bitcoin' },
  ETH: { name: 'Ethereum' },
  ADA: { name: 'Cardano' },
  BNB: { name: 'Binance Coin' },
  XRP: { name: 'Ripple' },
  DOGE: { name: 'Dogecoin' },
  LTC: { name: 'Litecoin' },
  DOT: { name: 'Polkadot' },
  LINK: { name: 'Chainlink' },
  SOL: { name: 'Solana' },
  TRX: { name: 'Tron' },
  MATIC: { name: 'Polygon' },
  UNI: { name: 'Uniswap' },
  AAVE: { name: 'Aave' },
  BSV: { name: 'Bitcoin SV' },
  CRO: { name: 'Crypto.com Coin' },
  FTT: { name: 'FTX Token' },
  SAND: { name: 'The Sandbox' },
  MANA: { name: 'Decentraland' },
  BAT: { name: 'Basic Attention Token' },
  ZRX: { name: '0x' },
  MKR: { name: 'Maker' },
  XTZ: { name: 'Tezos' },
  YFI: { name: 'yearn.finance' },
  COMP: { name: 'Compound' },
  REN: { name: 'Ren' },
  HBAR: { name: 'Hedera Hashgraph' },
  STX: { name: 'Stacks' },
  CVX: { name: 'Convex Finance' },
};

export { majorCurrencies, otherCurrencies, cryptocurrencies };
